// Generated by scripts/sdk-contract/generate-swift.py. Do not edit.
import Foundation

public struct Conversation: Sendable, Decodable, Hashable, Identifiable {
  public var acp: Bool?
  public var agentID: String?
  public var agentVersion: Int?
  public var agentVersionID: String?
  public var channelID: String?
  public var current: Bool?
  public var environmentID: String?
  public var firstPrompt: String?
  public var id: String
  public var insertedAt: Date?
  public var labels: [String: String]?
  public var lastActiveAt: Date?
  public var lastReadAt: Date?
  public var parentConversationID: String?
  public var pendingRequests: [PendingPermissionRequest]?
  public var permissionPolicyValues: [String: JSONValue]?
  public var runtime: Runtime
  public var runtimeSessionID: String?
  public var sandbox: Sandbox?
  public var sandboxAPIAccess: SandboxAPIAccess?
  public var sandboxID: String?
  public var source: ConversationSource?
  public var status: ConversationStatus
  public var title: String?
  public var turnCount: Int?
  public var unread: Bool?
  public var updatedAt: Date?
  public var usageTotal: Usage?
  public var vaultID: String?

  /// String verdicts for compatibility. Use permissionPolicyValues for numeric policy values.
  public var permissionPolicy: [String: String]? {
    get { permissionPolicyValues?.compactMapValues(\.stringValue) }
    set { permissionPolicyValues = newValue?.mapValues(JSONValue.string) }
  }

  enum CodingKeys: String, CodingKey {
    case acp = "acp"
    case agentID = "agent_id"
    case agentVersion = "agent_version"
    case agentVersionID = "agent_version_id"
    case channelID = "channel_id"
    case current = "current"
    case environmentID = "environment_id"
    case firstPrompt = "first_prompt"
    case id = "id"
    case insertedAt = "inserted_at"
    case labels = "labels"
    case lastActiveAt = "last_active_at"
    case lastReadAt = "last_read_at"
    case parentConversationID = "parent_conversation_id"
    case pendingRequests = "pending_requests"
    case permissionPolicyValues = "permission_policy"
    case runtime = "runtime"
    case runtimeSessionID = "runtime_session_id"
    case sandbox = "sandbox"
    case sandboxAPIAccess = "sandbox_api_access"
    case sandboxID = "sandbox_id"
    case source = "source"
    case status = "status"
    case title = "title"
    case turnCount = "turn_count"
    case unread = "unread"
    case updatedAt = "updated_at"
    case usageTotal = "usage_total"
    case vaultID = "vault_id"
  }
}

public struct Turn: Sendable, Decodable, Hashable, Identifiable {
  public var clientRequestID: String?
  public var endedAt: Date?
  public var exitCode: Int?
  public var id: String
  public var imageCount: Int?
  public var insertedAt: Date?
  public var limitReason: String?
  public var modelSelection: TurnModelSelection?
  public var origin: TurnOrigin?
  public var prompt: String
  public var startedAt: Date?
  public var status: TurnStatus
  public var turnNumber: Int
  public var usage: Usage?
  public var waiting: Bool?

  enum CodingKeys: String, CodingKey {
    case clientRequestID = "client_request_id"
    case endedAt = "ended_at"
    case exitCode = "exit_code"
    case id = "id"
    case imageCount = "image_count"
    case insertedAt = "inserted_at"
    case limitReason = "limit_reason"
    case modelSelection = "model_selection"
    case origin = "origin"
    case prompt = "prompt"
    case startedAt = "started_at"
    case status = "status"
    case turnNumber = "turn_number"
    case usage = "usage"
    case waiting = "waiting"
  }
}

public struct ConversationCreateRequest: Sendable, Encodable {
  public var agentID: String
  private var _channelID: ConversationInputField<String> = .omitted
  public var channelID: String? {
    get { _channelID.value }
    set { _channelID = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _clientRequestID: ConversationInputField<String> = .omitted
  public var clientRequestID: String? {
    get { _clientRequestID.value }
    set { _clientRequestID = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _environmentID: ConversationInputField<String> = .omitted
  public var environmentID: String? {
    get { _environmentID.value }
    set { _environmentID = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _fresh: ConversationInputField<Bool> = .omitted
  public var fresh: Bool? {
    get { _fresh.value }
    set { _fresh = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _images: ConversationInputField<[ImageInput]> = .omitted
  public var images: [ImageInput]? {
    get { _images.value }
    set { _images = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _inferenceCredentialID: ConversationInputField<String> = .omitted
  public var inferenceCredentialID: String? {
    get { _inferenceCredentialID.value }
    set { _inferenceCredentialID = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _labels: ConversationInputField<[String: String]> = .omitted
  public var labels: [String: String]? {
    get { _labels.value }
    set { _labels = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _permissionPolicyValues: ConversationInputField<[String: JSONValue]> = .omitted
  public var permissionPolicyValues: [String: JSONValue]? {
    get { _permissionPolicyValues.value }
    set { _permissionPolicyValues = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _prompt: ConversationInputField<String> = .omitted
  public var prompt: String? {
    get { _prompt.value }
    set { _prompt = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _queue: ConversationInputField<Bool> = .omitted
  public var queue: Bool? {
    get { _queue.value }
    set { _queue = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _sandboxAPIAccess: ConversationInputField<SandboxAPIAccess> = .omitted
  public var sandboxAPIAccess: SandboxAPIAccess? {
    get { _sandboxAPIAccess.value }
    set { _sandboxAPIAccess = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _sandboxID: ConversationInputField<String> = .omitted
  public var sandboxID: String? {
    get { _sandboxID.value }
    set { _sandboxID = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _sandboxMode: ConversationInputField<SandboxMode> = .omitted
  public var sandboxMode: SandboxMode? {
    get { _sandboxMode.value }
    set { _sandboxMode = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _spriteName: ConversationInputField<String> = .omitted
  public var spriteName: String? {
    get { _spriteName.value }
    set { _spriteName = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _title: ConversationInputField<String> = .omitted
  public var title: String? {
    get { _title.value }
    set { _title = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _vaultID: ConversationInputField<String> = .omitted
  public var vaultID: String? {
    get { _vaultID.value }
    set { _vaultID = newValue.map(ConversationInputField.value) ?? .omitted }
  }

  /// String verdicts for compatibility. Use permissionPolicyValues for numeric policy values.
  public var permissionPolicy: [String: String]? {
    get { permissionPolicyValues?.compactMapValues(\.stringValue) }
    set { permissionPolicyValues = newValue?.mapValues(JSONValue.string) }
  }

  public init(
    agentID: String,
    prompt: String? = nil,
    title: String? = nil,
    vaultID: String? = nil,
    environmentID: String? = nil,
    permissionPolicy: [String: String]? = nil,
    images: [ImageInput]? = nil,
    spriteName: String? = nil,
    sandboxMode: SandboxMode? = nil,
    sandboxAPIAccess: SandboxAPIAccess? = nil,
    sandboxID: String? = nil,
    channelID: String? = nil,
    fresh: Bool? = nil,
    clientRequestID: String? = nil,
    inferenceCredentialID: String? = nil,
    labels: [String: String]? = nil,
    queue: Bool? = nil
  ) {
    self.agentID = agentID
    self.prompt = prompt
    self.title = title
    self.vaultID = vaultID
    self.environmentID = environmentID
    self.permissionPolicyValues = permissionPolicy?.mapValues(JSONValue.string)
    self.images = images
    self.spriteName = spriteName
    self.sandboxMode = sandboxMode
    self.sandboxAPIAccess = sandboxAPIAccess
    self.sandboxID = sandboxID
    self.channelID = channelID
    self.fresh = fresh
    self.clientRequestID = clientRequestID
    self.inferenceCredentialID = inferenceCredentialID
    self.labels = labels
    self.queue = queue
  }

  enum CodingKeys: String, CodingKey {
    case agentID = "agent_id"
    case channelID = "channel_id"
    case clientRequestID = "client_request_id"
    case environmentID = "environment_id"
    case fresh = "fresh"
    case images = "images"
    case inferenceCredentialID = "inference_credential_id"
    case labels = "labels"
    case permissionPolicyValues = "permission_policy"
    case prompt = "prompt"
    case queue = "queue"
    case sandboxAPIAccess = "sandbox_api_access"
    case sandboxID = "sandbox_id"
    case sandboxMode = "sandbox_mode"
    case spriteName = "sprite_name"
    case title = "title"
    case vaultID = "vault_id"
  }

  /// Fields for which the API accepts an explicit JSON null.
  public enum NullableField: Sendable {
    case channelID
    case clientRequestID
    case environmentID
    case fresh
    case images
    case inferenceCredentialID
    case labels
    case permissionPolicyValues
    case queue
    case sandboxID
    case sandboxMode
    case title
    case vaultID
  }

  /// Send null. Assigning the property nil again restores omission.
  public mutating func setNull(_ field: NullableField) {
    switch field {
    case .channelID: _channelID = .null
    case .clientRequestID: _clientRequestID = .null
    case .environmentID: _environmentID = .null
    case .fresh: _fresh = .null
    case .images: _images = .null
    case .inferenceCredentialID: _inferenceCredentialID = .null
    case .labels: _labels = .null
    case .permissionPolicyValues: _permissionPolicyValues = .null
    case .queue: _queue = .null
    case .sandboxID: _sandboxID = .null
    case .sandboxMode: _sandboxMode = .null
    case .title: _title = .null
    case .vaultID: _vaultID = .null
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(agentID, forKey: .agentID)
    try _channelID.encode(into: &container, forKey: .channelID)
    try _clientRequestID.encode(into: &container, forKey: .clientRequestID)
    try _environmentID.encode(into: &container, forKey: .environmentID)
    try _fresh.encode(into: &container, forKey: .fresh)
    try _images.encode(into: &container, forKey: .images)
    try _inferenceCredentialID.encode(into: &container, forKey: .inferenceCredentialID)
    try _labels.encode(into: &container, forKey: .labels)
    try _permissionPolicyValues.encode(into: &container, forKey: .permissionPolicyValues)
    try _prompt.encode(into: &container, forKey: .prompt)
    try _queue.encode(into: &container, forKey: .queue)
    try _sandboxAPIAccess.encode(into: &container, forKey: .sandboxAPIAccess)
    try _sandboxID.encode(into: &container, forKey: .sandboxID)
    try _sandboxMode.encode(into: &container, forKey: .sandboxMode)
    try _spriteName.encode(into: &container, forKey: .spriteName)
    try _title.encode(into: &container, forKey: .title)
    try _vaultID.encode(into: &container, forKey: .vaultID)
  }
}

public struct ImageInput: Sendable, Encodable {
  public var data: String
  public var mediaType: String

  public init(
    data: String,
    mediaType: String
  ) {
    self.data = data
    self.mediaType = mediaType
  }

  enum CodingKeys: String, CodingKey {
    case data = "data"
    case mediaType = "media_type"
  }
}

public struct Usage: Sendable, Decodable, Hashable {
  public var accounting: UsageAccounting?
  public var cacheRead: Int?
  public var cacheWrite: Int?
  public var input: Int?
  public var output: Int?

  enum CodingKeys: String, CodingKey {
    case accounting = "accounting"
    case cacheRead = "cache_read"
    case cacheWrite = "cache_write"
    case input = "input"
    case output = "output"
  }
}

public struct UsageAccounting: Sendable, Decodable, Hashable {
  public var completeness: String
  public var scope: String
  public var source: String
  public var version: Int

  enum CodingKeys: String, CodingKey {
    case completeness = "completeness"
    case scope = "scope"
    case source = "source"
    case version = "version"
  }
}

public struct SandboxDetail: Sendable, Decodable, Hashable, Identifiable {
  public var agentID: String?
  public var checkpoint: Sandbox.Checkpoint?
  public var conversations: [SandboxDetail.SandboxConversation]?
  public var environmentID: String?
  public var id: String
  public var insertedAt: Date?
  public var lastResumedAt: Date?
  public var mode: SandboxMode?
  public var provider: SandboxProvider?
  public var runner: Sandbox.RunnerRef?
  public var spriteName: String?
  public var status: SandboxStatus?
  public var url: String?
  public var vaultID: String?

  enum CodingKeys: String, CodingKey {
    case agentID = "agent_id"
    case checkpoint = "checkpoint"
    case conversations = "conversations"
    case environmentID = "environment_id"
    case id = "id"
    case insertedAt = "inserted_at"
    case lastResumedAt = "last_resumed_at"
    case mode = "mode"
    case provider = "provider"
    case runner = "runner"
    case spriteName = "sprite_name"
    case status = "status"
    case url = "url"
    case vaultID = "vault_id"
  }
}

public struct Runner: Sendable, Decodable, Hashable, Identifiable {
  public var arch: String?
  public var connectedAt: Date?
  public var createdAt: Date?
  public var hostname: String?
  public var id: String
  public var lastSeenAt: Date?
  public var name: String
  public var online: Bool
  public var os: String?
  public var root: String?
  public var version: String?

  enum CodingKeys: String, CodingKey {
    case arch = "arch"
    case connectedAt = "connected_at"
    case createdAt = "created_at"
    case hostname = "hostname"
    case id = "id"
    case lastSeenAt = "last_seen_at"
    case name = "name"
    case online = "online"
    case os = "os"
    case root = "root"
    case version = "version"
  }
}

public struct ConversationTreeNode: Sendable, Decodable, Hashable, Identifiable {
  public var id: String
  public var parentID: String?
  public var source: ConversationSource?
  public var status: ConversationStatus?

  enum CodingKeys: String, CodingKey {
    case id = "id"
    case parentID = "parent_id"
    case source = "source"
    case status = "status"
  }
}

public struct Agent: Sendable, Decodable, Hashable, Identifiable {
  public var acp: Bool?
  public var allowedEnvironmentIDs: [String]?
  public var allowedInferenceCredentialIDs: [String]?
  public var allowedVaultIDs: [String]?
  public var avatarMediaType: String?
  public var conversationCount: Int?
  public var description: String?
  public var environmentID: String?
  public var id: String
  public var inferenceCredentialID: String?
  public var insertedAt: Date?
  public var mcpServers: JSONValue?
  public var metadata: JSONValue?
  public var model: String?
  public var name: String
  public var permissionPolicyValues: [String: JSONValue]?
  public var runtime: Runtime
  public var runtimeCommand: String?
  public var sandboxMode: SandboxMode?
  public var sandboxProvider: SandboxProvider?
  public var skills: [Skill]?
  public var system: String?
  public var updatedAt: Date?

  /// String verdicts for compatibility. Use permissionPolicyValues for numeric policy values.
  public var permissionPolicy: [String: String]? {
    get { permissionPolicyValues?.compactMapValues(\.stringValue) }
    set { permissionPolicyValues = newValue?.mapValues(JSONValue.string) }
  }

  enum CodingKeys: String, CodingKey {
    case acp = "acp"
    case allowedEnvironmentIDs = "allowed_environment_ids"
    case allowedInferenceCredentialIDs = "allowed_inference_credential_ids"
    case allowedVaultIDs = "allowed_vault_ids"
    case avatarMediaType = "avatar_media_type"
    case conversationCount = "conversation_count"
    case description = "description"
    case environmentID = "environment_id"
    case id = "id"
    case inferenceCredentialID = "inference_credential_id"
    case insertedAt = "inserted_at"
    case mcpServers = "mcp_servers"
    case metadata = "metadata"
    case model = "model"
    case name = "name"
    case permissionPolicyValues = "permission_policy"
    case runtime = "runtime"
    case runtimeCommand = "runtime_command"
    case sandboxMode = "sandbox_mode"
    case sandboxProvider = "sandbox_provider"
    case skills = "skills"
    case system = "system"
    case updatedAt = "updated_at"
  }
}

public struct AgentVersion: Sendable, Decodable, Hashable, Identifiable {
  public var agentID: String
  public var config: JSONValue?
  public var id: String
  public var insertedAt: Date?
  public var version: Int

  enum CodingKeys: String, CodingKey {
    case agentID = "agent_id"
    case config = "config"
    case id = "id"
    case insertedAt = "inserted_at"
    case version = "version"
  }
}

public struct AgentInput: Sendable, Encodable {
  private var _allowedEnvironmentIDs: ConversationInputField<[String]> = .omitted
  public var allowedEnvironmentIDs: [String]? {
    get { _allowedEnvironmentIDs.value }
    set { _allowedEnvironmentIDs = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _allowedInferenceCredentialIDs: ConversationInputField<[String]> = .omitted
  public var allowedInferenceCredentialIDs: [String]? {
    get { _allowedInferenceCredentialIDs.value }
    set { _allowedInferenceCredentialIDs = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _allowedVaultIDs: ConversationInputField<[String]> = .omitted
  public var allowedVaultIDs: [String]? {
    get { _allowedVaultIDs.value }
    set { _allowedVaultIDs = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _description: ConversationInputField<String> = .omitted
  public var description: String? {
    get { _description.value }
    set { _description = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _environmentID: ConversationInputField<String> = .omitted
  public var environmentID: String? {
    get { _environmentID.value }
    set { _environmentID = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _inferenceCredentialID: ConversationInputField<String> = .omitted
  public var inferenceCredentialID: String? {
    get { _inferenceCredentialID.value }
    set { _inferenceCredentialID = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _mcpServers: ConversationInputField<JSONValue> = .omitted
  public var mcpServers: JSONValue? {
    get { _mcpServers.value }
    set { _mcpServers = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _metadata: ConversationInputField<JSONValue> = .omitted
  public var metadata: JSONValue? {
    get { _metadata.value }
    set { _metadata = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _model: ConversationInputField<String> = .omitted
  public var model: String? {
    get { _model.value }
    set { _model = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _name: ConversationInputField<String> = .omitted
  public var name: String? {
    get { _name.value }
    set { _name = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _permissionPolicyValues: ConversationInputField<[String: JSONValue]> = .omitted
  public var permissionPolicyValues: [String: JSONValue]? {
    get { _permissionPolicyValues.value }
    set { _permissionPolicyValues = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _runtime: ConversationInputField<Runtime> = .omitted
  public var runtime: Runtime? {
    get { _runtime.value }
    set { _runtime = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _runtimeCommand: ConversationInputField<String> = .omitted
  public var runtimeCommand: String? {
    get { _runtimeCommand.value }
    set { _runtimeCommand = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _sandboxMode: ConversationInputField<SandboxMode> = .omitted
  public var sandboxMode: SandboxMode? {
    get { _sandboxMode.value }
    set { _sandboxMode = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _sandboxProvider: ConversationInputField<SandboxProvider> = .omitted
  public var sandboxProvider: SandboxProvider? {
    get { _sandboxProvider.value }
    set { _sandboxProvider = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _skills: ConversationInputField<[Skill]> = .omitted
  public var skills: [Skill]? {
    get { _skills.value }
    set { _skills = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _system: ConversationInputField<String> = .omitted
  public var system: String? {
    get { _system.value }
    set { _system = newValue.map(ConversationInputField.value) ?? .omitted }
  }

  /// String verdicts for compatibility. Use permissionPolicyValues for numeric policy values.
  public var permissionPolicy: [String: String]? {
    get { permissionPolicyValues?.compactMapValues(\.stringValue) }
    set { permissionPolicyValues = newValue?.mapValues(JSONValue.string) }
  }

  public init(
    name: String? = nil,
    description: String? = nil,
    system: String? = nil,
    model: String? = nil,
    runtime: Runtime? = nil,
    runtimeCommand: String? = nil,
    sandboxProvider: SandboxProvider? = nil,
    sandboxMode: SandboxMode? = nil,
    environmentID: String? = nil,
    permissionPolicy: [String: String]? = nil,
    skills: [Skill]? = nil,
    mcpServers: JSONValue? = nil,
    metadata: JSONValue? = nil,
    allowedVaultIDs: [String]? = nil,
    allowedEnvironmentIDs: [String]? = nil,
    allowedInferenceCredentialIDs: [String]? = nil,
    inferenceCredentialID: String? = nil
  ) {
    self.name = name
    self.description = description
    self.system = system
    self.model = model
    self.runtime = runtime
    self.runtimeCommand = runtimeCommand
    self.sandboxProvider = sandboxProvider
    self.sandboxMode = sandboxMode
    self.environmentID = environmentID
    self.permissionPolicyValues = permissionPolicy?.mapValues(JSONValue.string)
    self.skills = skills
    self.mcpServers = mcpServers
    self.metadata = metadata
    self.allowedVaultIDs = allowedVaultIDs
    self.allowedEnvironmentIDs = allowedEnvironmentIDs
    self.allowedInferenceCredentialIDs = allowedInferenceCredentialIDs
    self.inferenceCredentialID = inferenceCredentialID
  }

  enum CodingKeys: String, CodingKey {
    case allowedEnvironmentIDs = "allowed_environment_ids"
    case allowedInferenceCredentialIDs = "allowed_inference_credential_ids"
    case allowedVaultIDs = "allowed_vault_ids"
    case description = "description"
    case environmentID = "environment_id"
    case inferenceCredentialID = "inference_credential_id"
    case mcpServers = "mcp_servers"
    case metadata = "metadata"
    case model = "model"
    case name = "name"
    case permissionPolicyValues = "permission_policy"
    case runtime = "runtime"
    case runtimeCommand = "runtime_command"
    case sandboxMode = "sandbox_mode"
    case sandboxProvider = "sandbox_provider"
    case skills = "skills"
    case system = "system"
  }

  /// Fields for which the API accepts an explicit JSON null.
  public enum NullableField: Sendable {
    case allowedEnvironmentIDs
    case allowedInferenceCredentialIDs
    case allowedVaultIDs
    case environmentID
    case inferenceCredentialID
    case model
    case permissionPolicyValues
    case runtimeCommand
    case sandboxProvider
  }

  /// Send null. Assigning the property nil again restores omission.
  public mutating func setNull(_ field: NullableField) {
    switch field {
    case .allowedEnvironmentIDs: _allowedEnvironmentIDs = .null
    case .allowedInferenceCredentialIDs: _allowedInferenceCredentialIDs = .null
    case .allowedVaultIDs: _allowedVaultIDs = .null
    case .environmentID: _environmentID = .null
    case .inferenceCredentialID: _inferenceCredentialID = .null
    case .model: _model = .null
    case .permissionPolicyValues: _permissionPolicyValues = .null
    case .runtimeCommand: _runtimeCommand = .null
    case .sandboxProvider: _sandboxProvider = .null
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try _allowedEnvironmentIDs.encode(into: &container, forKey: .allowedEnvironmentIDs)
    try _allowedInferenceCredentialIDs.encode(
      into: &container, forKey: .allowedInferenceCredentialIDs)
    try _allowedVaultIDs.encode(into: &container, forKey: .allowedVaultIDs)
    try _description.encode(into: &container, forKey: .description)
    try _environmentID.encode(into: &container, forKey: .environmentID)
    try _inferenceCredentialID.encode(into: &container, forKey: .inferenceCredentialID)
    try _mcpServers.encode(into: &container, forKey: .mcpServers)
    try _metadata.encode(into: &container, forKey: .metadata)
    try _model.encode(into: &container, forKey: .model)
    try _name.encode(into: &container, forKey: .name)
    try _permissionPolicyValues.encode(into: &container, forKey: .permissionPolicyValues)
    try _runtime.encode(into: &container, forKey: .runtime)
    try _runtimeCommand.encode(into: &container, forKey: .runtimeCommand)
    try _sandboxMode.encode(into: &container, forKey: .sandboxMode)
    try _sandboxProvider.encode(into: &container, forKey: .sandboxProvider)
    try _skills.encode(into: &container, forKey: .skills)
    try _system.encode(into: &container, forKey: .system)
  }
}

public struct Environment: Sendable, Decodable, Hashable, Identifiable {
  public var agentCount: Int?
  public var envVars: [String: String]?
  public var id: String
  public var insertedAt: Date?
  public var metadata: JSONValue?
  public var name: String
  public var networkingConfig: JSONValue?
  public var networkingType: NetworkingType?
  public var packages: JSONValue?
  public var repositories: [JSONValue]?
  public var secretCount: Int?
  public var setupScript: String?
  public var setupTimeoutSeconds: Int?
  public var updatedAt: Date?

  enum CodingKeys: String, CodingKey {
    case agentCount = "agent_count"
    case envVars = "env_vars"
    case id = "id"
    case insertedAt = "inserted_at"
    case metadata = "metadata"
    case name = "name"
    case networkingConfig = "networking_config"
    case networkingType = "networking_type"
    case packages = "packages"
    case repositories = "repositories"
    case secretCount = "secret_count"
    case setupScript = "setup_script"
    case setupTimeoutSeconds = "setup_timeout_seconds"
    case updatedAt = "updated_at"
  }
}

public struct EnvironmentInput: Sendable, Encodable {
  public var envVars: [String: String]?
  public var metadata: JSONValue?
  public var name: String?
  public var networkingConfig: JSONValue?
  public var networkingType: NetworkingType?
  public var packages: JSONValue?
  public var repositories: [JSONValue]?
  public var setupScript: String?
  public var setupTimeoutSeconds: Int?

  public init(
    name: String? = nil,
    packages: JSONValue? = nil,
    envVars: [String: String]? = nil,
    setupScript: String? = nil,
    setupTimeoutSeconds: Int? = nil,
    networkingType: NetworkingType? = nil,
    networkingConfig: JSONValue? = nil,
    repositories: [JSONValue]? = nil,
    metadata: JSONValue? = nil
  ) {
    self.name = name
    self.packages = packages
    self.envVars = envVars
    self.setupScript = setupScript
    self.setupTimeoutSeconds = setupTimeoutSeconds
    self.networkingType = networkingType
    self.networkingConfig = networkingConfig
    self.repositories = repositories
    self.metadata = metadata
  }

  enum CodingKeys: String, CodingKey {
    case envVars = "env_vars"
    case metadata = "metadata"
    case name = "name"
    case networkingConfig = "networking_config"
    case networkingType = "networking_type"
    case packages = "packages"
    case repositories = "repositories"
    case setupScript = "setup_script"
    case setupTimeoutSeconds = "setup_timeout_seconds"
  }
}

public struct Vault: Sendable, Decodable, Hashable, Identifiable {
  public var description: String?
  public var id: String
  public var insertedAt: Date?
  public var metadata: JSONValue?
  public var name: String
  public var secretCount: Int?
  public var updatedAt: Date?

  enum CodingKeys: String, CodingKey {
    case description = "description"
    case id = "id"
    case insertedAt = "inserted_at"
    case metadata = "metadata"
    case name = "name"
    case secretCount = "secret_count"
    case updatedAt = "updated_at"
  }
}

public struct VaultInput: Sendable, Encodable {
  public var description: String?
  public var metadata: JSONValue?
  public var name: String?

  public init(
    name: String? = nil,
    description: String? = nil,
    metadata: JSONValue? = nil
  ) {
    self.name = name
    self.description = description
    self.metadata = metadata
  }

  enum CodingKeys: String, CodingKey {
    case description = "description"
    case metadata = "metadata"
    case name = "name"
  }
}

public struct Secret: Sendable, Decodable, Hashable, Identifiable {
  public var environmentID: String?
  public var expiresAt: Date?
  public var id: String
  public var insertedAt: Date?
  public var key: String
  public var updatedAt: Date?
  public var vaultID: String?

  enum CodingKeys: String, CodingKey {
    case environmentID = "environment_id"
    case expiresAt = "expires_at"
    case id = "id"
    case insertedAt = "inserted_at"
    case key = "key"
    case updatedAt = "updated_at"
    case vaultID = "vault_id"
  }
}

public struct Connection: Sendable, Decodable, Hashable, Identifiable {
  public var accountEmail: String?
  public var createdAt: Date?
  public var envKey: String?
  public var expiresAt: Date?
  public var id: String
  public var provider: String
  public var providerID: String?
  public var revokedAt: Date?
  public var scopes: [String]?
  public var status: ConnectionStatus?
  public var updatedAt: Date?

  enum CodingKeys: String, CodingKey {
    case accountEmail = "account_email"
    case createdAt = "created_at"
    case envKey = "env_key"
    case expiresAt = "expires_at"
    case id = "id"
    case provider = "provider"
    case providerID = "provider_id"
    case revokedAt = "revoked_at"
    case scopes = "scopes"
    case status = "status"
    case updatedAt = "updated_at"
  }
}

public struct ConnectionProvider: Sendable, Decodable, Hashable, Identifiable {
  public var accountLabelPath: String?
  public var authorizeURL: String?
  public var clientID: String?
  public var clientSource: String?
  public var configured: Bool?
  public var connectURL: String?
  public var createdAt: Date?
  public var envKey: String?
  public var hasClientSecret: Bool?
  public var id: String
  public var issuer: String?
  public var kind: String?
  public var mcpURL: String?
  public var name: String?
  public var pkce: Bool?
  public var platform: Bool?
  public var redirectURI: String?
  public var registrationEndpoint: String?
  public var revokeURL: String?
  public var scopes: [String]?
  public var slug: String?
  public var tokenEndpointAuth: String?
  public var tokenHosts: [String]?
  public var tokenURL: String?
  public var updatedAt: Date?
  public var userinfoURL: String?

  enum CodingKeys: String, CodingKey {
    case accountLabelPath = "account_label_path"
    case authorizeURL = "authorize_url"
    case clientID = "client_id"
    case clientSource = "client_source"
    case configured = "configured"
    case connectURL = "connect_url"
    case createdAt = "created_at"
    case envKey = "env_key"
    case hasClientSecret = "has_client_secret"
    case id = "id"
    case issuer = "issuer"
    case kind = "kind"
    case mcpURL = "mcp_url"
    case name = "name"
    case pkce = "pkce"
    case platform = "platform"
    case redirectURI = "redirect_uri"
    case registrationEndpoint = "registration_endpoint"
    case revokeURL = "revoke_url"
    case scopes = "scopes"
    case slug = "slug"
    case tokenEndpointAuth = "token_endpoint_auth"
    case tokenHosts = "token_hosts"
    case tokenURL = "token_url"
    case updatedAt = "updated_at"
    case userinfoURL = "userinfo_url"
  }
}

public struct Teammate: Sendable, Decodable, Hashable, Identifiable {
  public var agent: Agent
  public var agentID: String
  public var conversation: Conversation
  public var lastTurn: Teammate.LastTurn?
  public var name: String
  public var presence: Teammate.Presence
  public var preview: Teammate.Preview?
  public var unread: Bool
  public var usageTotal: Usage?
  public var id: String { agentID }

  enum CodingKeys: String, CodingKey {
    case agent = "agent"
    case agentID = "agent_id"
    case conversation = "conversation"
    case lastTurn = "last_turn"
    case name = "name"
    case presence = "presence"
    case preview = "preview"
    case unread = "unread"
    case usageTotal = "usage_total"
  }
}

public struct TeamSchedule: Sendable, Decodable, Hashable, Identifiable {
  public var agentID: String
  public var cron: String
  public var enabled: Bool?
  public var id: String
  public var insertedAt: Date?
  public var lastConversationID: String?
  public var lastError: String?
  public var lastRunAt: Date?
  public var name: String?
  public var nextRunAt: Date?
  public var oneOff: Bool?
  public var prompt: String
  public var updatedAt: Date?

  enum CodingKeys: String, CodingKey {
    case agentID = "agent_id"
    case cron = "cron"
    case enabled = "enabled"
    case id = "id"
    case insertedAt = "inserted_at"
    case lastConversationID = "last_conversation_id"
    case lastError = "last_error"
    case lastRunAt = "last_run_at"
    case name = "name"
    case nextRunAt = "next_run_at"
    case oneOff = "one_off"
    case prompt = "prompt"
    case updatedAt = "updated_at"
  }
}

public struct TeamScheduleInput: Sendable, Encodable {
  private var _cron: ConversationInputField<String> = .omitted
  public var cron: String? {
    get { _cron.value }
    set { _cron = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _enabled: ConversationInputField<Bool> = .omitted
  public var enabled: Bool? {
    get { _enabled.value }
    set { _enabled = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _name: ConversationInputField<String> = .omitted
  public var name: String? {
    get { _name.value }
    set { _name = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _oneOff: ConversationInputField<Bool> = .omitted
  public var oneOff: Bool? {
    get { _oneOff.value }
    set { _oneOff = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _prompt: ConversationInputField<String> = .omitted
  public var prompt: String? {
    get { _prompt.value }
    set { _prompt = newValue.map(ConversationInputField.value) ?? .omitted }
  }

  public init(
    cron: String? = nil,
    prompt: String? = nil,
    name: String? = nil,
    oneOff: Bool? = nil,
    enabled: Bool? = nil
  ) {
    self.cron = cron
    self.prompt = prompt
    self.name = name
    self.oneOff = oneOff
    self.enabled = enabled
  }

  enum CodingKeys: String, CodingKey {
    case cron = "cron"
    case enabled = "enabled"
    case name = "name"
    case oneOff = "one_off"
    case prompt = "prompt"
  }

  /// Fields for which the API accepts an explicit JSON null.
  public enum NullableField: Sendable {
    case name
  }

  /// Send null. Assigning the property nil again restores omission.
  public mutating func setNull(_ field: NullableField) {
    switch field {
    case .name: _name = .null
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try _cron.encode(into: &container, forKey: .cron)
    try _enabled.encode(into: &container, forKey: .enabled)
    try _name.encode(into: &container, forKey: .name)
    try _oneOff.encode(into: &container, forKey: .oneOff)
    try _prompt.encode(into: &container, forKey: .prompt)
  }
}

public struct TeamAddRequest: Sendable, Encodable {
  public var agentID: String
  private var _environmentID: ConversationInputField<String> = .omitted
  public var environmentID: String? {
    get { _environmentID.value }
    set { _environmentID = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _name: ConversationInputField<String> = .omitted
  public var name: String? {
    get { _name.value }
    set { _name = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _vaultID: ConversationInputField<String> = .omitted
  public var vaultID: String? {
    get { _vaultID.value }
    set { _vaultID = newValue.map(ConversationInputField.value) ?? .omitted }
  }

  public init(
    agentID: String,
    name: String? = nil,
    environmentID: String? = nil,
    vaultID: String? = nil
  ) {
    self.agentID = agentID
    self.name = name
    self.environmentID = environmentID
    self.vaultID = vaultID
  }

  enum CodingKeys: String, CodingKey {
    case agentID = "agent_id"
    case environmentID = "environment_id"
    case name = "name"
    case vaultID = "vault_id"
  }

  /// Fields for which the API accepts an explicit JSON null.
  public enum NullableField: Sendable {
    case environmentID
    case name
    case vaultID
  }

  /// Send null. Assigning the property nil again restores omission.
  public mutating func setNull(_ field: NullableField) {
    switch field {
    case .environmentID: _environmentID = .null
    case .name: _name = .null
    case .vaultID: _vaultID = .null
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(agentID, forKey: .agentID)
    try _environmentID.encode(into: &container, forKey: .environmentID)
    try _name.encode(into: &container, forKey: .name)
    try _vaultID.encode(into: &container, forKey: .vaultID)
  }
}

public struct TeamRenameRequest: Sendable, Encodable {
  private var _name: ConversationInputField<String> = .omitted
  public var name: String? {
    get { _name.value }
    set { _name = newValue.map(ConversationInputField.value) ?? .omitted }
  }

  public init(
    name: String? = nil
  ) {
    self.name = name
  }

  enum CodingKeys: String, CodingKey {
    case name = "name"
  }

  /// Fields for which the API accepts an explicit JSON null.
  public enum NullableField: Sendable {
    case name
  }

  /// Send null. Assigning the property nil again restores omission.
  public mutating func setNull(_ field: NullableField) {
    switch field {
    case .name: _name = .null
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try _name.encode(into: &container, forKey: .name)
  }
}

public struct TeamMessageRequest: Sendable, Encodable {
  private var _images: ConversationInputField<[ImageInput]> = .omitted
  public var images: [ImageInput]? {
    get { _images.value }
    set { _images = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  private var _labels: ConversationInputField<[String: JSONValue]> = .omitted
  public var labels: [String: JSONValue]? {
    get { _labels.value }
    set { _labels = newValue.map(ConversationInputField.value) ?? .omitted }
  }
  public var prompt: String

  public init(
    prompt: String,
    images: [ImageInput]? = nil,
    labels: [String: JSONValue]? = nil
  ) {
    self.prompt = prompt
    self.images = images
    self.labels = labels
  }

  enum CodingKeys: String, CodingKey {
    case images = "images"
    case labels = "labels"
    case prompt = "prompt"
  }

  /// Fields for which the API accepts an explicit JSON null.
  public enum NullableField: Sendable {
    case images
    case labels
  }

  /// Send null. Assigning the property nil again restores omission.
  public mutating func setNull(_ field: NullableField) {
    switch field {
    case .images: _images = .null
    case .labels: _labels = .null
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try _images.encode(into: &container, forKey: .images)
    try _labels.encode(into: &container, forKey: .labels)
    try container.encode(prompt, forKey: .prompt)
  }
}

public struct APIKey: Sendable, Decodable, Hashable, Identifiable {
  public var createdAt: Date?
  public var expiresAt: Date?
  public var id: String
  public var lastUsedAt: Date?
  public var name: String
  public var prefix: String?
  public var scopes: [String]?

  enum CodingKeys: String, CodingKey {
    case createdAt = "created_at"
    case expiresAt = "expires_at"
    case id = "id"
    case lastUsedAt = "last_used_at"
    case name = "name"
    case prefix = "prefix"
    case scopes = "scopes"
  }
}

public struct CreatedAPIKey: Sendable, Decodable, Hashable, Identifiable {
  public var createdAt: Date?
  public var id: String
  public var key: String
  public var name: String?
  public var prefix: String?

  enum CodingKeys: String, CodingKey {
    case createdAt = "created_at"
    case id = "id"
    case key = "key"
    case name = "name"
    case prefix = "prefix"
  }
}

public struct AuditEvent: Sendable, Decodable, Hashable, Identifiable {
  public var action: String
  public var actor: String?
  public var id: Int
  public var insertedAt: Date?
  public var metadata: JSONValue?
  public var requestIP: String?
  public var resourceID: String?
  public var resourceType: String?

  enum CodingKeys: String, CodingKey {
    case action = "action"
    case actor = "actor"
    case id = "id"
    case insertedAt = "inserted_at"
    case metadata = "metadata"
    case requestIP = "request_ip"
    case resourceID = "resource_id"
    case resourceType = "resource_type"
  }
}

public struct SearchHit: Sendable, Decodable, Hashable {
  public var agentID: String?
  public var conversationID: String
  public var kind: SearchHitKind
  public var snippet: String?
  public var ts: Date?
  public var turnID: String?
  public var turnNumber: Int?

  enum CodingKeys: String, CodingKey {
    case agentID = "agent_id"
    case conversationID = "conversation_id"
    case kind = "kind"
    case snippet = "snippet"
    case ts = "ts"
    case turnID = "turn_id"
    case turnNumber = "turn_number"
  }
}

public struct Catalog: Sendable, Decodable, Hashable {
  public var apps: Catalog.Apps?
  public var firstRequest: CatalogFirstRequest?
  public var mcpServers: [CatalogMcpServersItem]?
  public var modelProviders: [String]?
  public var models: [String: [String]]?
  public var packageManagers: [String]?
  public var runtimes: [String]?
  public var sandboxAPIAccess: [SandboxAPIAccess]?
  public var sandboxProviders: Catalog.SandboxProviders?

  enum CodingKeys: String, CodingKey {
    case apps = "apps"
    case firstRequest = "first_request"
    case mcpServers = "mcp_servers"
    case modelProviders = "model_providers"
    case models = "models"
    case packageManagers = "package_managers"
    case runtimes = "runtimes"
    case sandboxAPIAccess = "sandbox_api_access"
    case sandboxProviders = "sandbox_providers"
  }
}

public struct ApplyResult: Sendable, Decodable, Hashable {
  public var action: String
  public var errors: JSONValue?
  public var kind: String
  public var name: String
  public var secret: String?
  public var secrets: [ApplyResult.SecretResult]?

  enum CodingKeys: String, CodingKey {
    case action = "action"
    case errors = "errors"
    case kind = "kind"
    case name = "name"
    case secret = "secret"
    case secrets = "secrets"
  }
}

public struct AdminUser: Sendable, Decodable, Hashable, Identifiable {
  public var activeSandboxes: Int?
  public var comped: Bool?
  public var creditBalanceCents: Int?
  public var email: String
  public var emailVerified: Bool?
  public var emailVerifiedAt: Date?
  public var hasStripeCustomer: Bool?
  public var id: String
  public var insertedAt: Date?
  public var lastActivityAt: Date?
  public var maxConcurrentSandboxes: Int?
  public var onboardingCompletedAt: Date?
  public var role: UserRole?
  public var sandboxLimitOverride: Int?
  public var suspended: Bool?
  public var suspendedAt: Date?

  enum CodingKeys: String, CodingKey {
    case activeSandboxes = "active_sandboxes"
    case comped = "comped"
    case creditBalanceCents = "credit_balance_cents"
    case email = "email"
    case emailVerified = "email_verified"
    case emailVerifiedAt = "email_verified_at"
    case hasStripeCustomer = "has_stripe_customer"
    case id = "id"
    case insertedAt = "inserted_at"
    case lastActivityAt = "last_activity_at"
    case maxConcurrentSandboxes = "max_concurrent_sandboxes"
    case onboardingCompletedAt = "onboarding_completed_at"
    case role = "role"
    case sandboxLimitOverride = "sandbox_limit_override"
    case suspended = "suspended"
    case suspendedAt = "suspended_at"
  }
}

public struct AdminSandbox: Sendable, Decodable, Hashable, Identifiable {
  public var conversationCount: Int?
  public var id: String
  public var insertedAt: Date?
  public var provider: SandboxProvider?
  public var spriteName: String?
  public var status: SandboxStatus?
  public var updatedAt: Date?
  public var userEmail: String?
  public var userID: String?

  enum CodingKeys: String, CodingKey {
    case conversationCount = "conversation_count"
    case id = "id"
    case insertedAt = "inserted_at"
    case provider = "provider"
    case spriteName = "sprite_name"
    case status = "status"
    case updatedAt = "updated_at"
    case userEmail = "user_email"
    case userID = "user_id"
  }
}

public struct AdminEvent: Sendable, Decodable, Hashable, Identifiable {
  public var actorUserID: String?
  public var eventType: String
  public var id: Int?
  public var insertedAt: Date?
  public var metadata: JSONValue?
  public var targetUserID: String?

  enum CodingKeys: String, CodingKey {
    case actorUserID = "actor_user_id"
    case eventType = "event_type"
    case id = "id"
    case insertedAt = "inserted_at"
    case metadata = "metadata"
    case targetUserID = "target_user_id"
  }
}

public struct AuthMe: Sendable, Decodable, Hashable, Identifiable {
  public var brokered: Bool?
  public var comped: Bool?
  public var connectionsEnabled: Bool?
  public var connectionsManageable: Bool?
  public var email: String
  public var emailVerified: Bool?
  public var expiresAt: Date?
  public var id: String
  public var onboardingCompleted: Bool?
  public var role: UserRole?

  enum CodingKeys: String, CodingKey {
    case brokered = "brokered"
    case comped = "comped"
    case connectionsEnabled = "connections_enabled"
    case connectionsManageable = "connections_manageable"
    case email = "email"
    case emailVerified = "email_verified"
    case expiresAt = "expires_at"
    case id = "id"
    case onboardingCompleted = "onboarding_completed"
    case role = "role"
  }
}

public struct AdminUserListResponse: Sendable, Decodable, Hashable {
  public var data: [AdminUser]
  public var meta: AdminUserListResponse.Meta

  enum CodingKeys: String, CodingKey {
    case data = "data"
    case meta = "meta"
  }
}

public struct LogEvent: Sendable, Decodable, Hashable, Identifiable {
  public var agentID: String?
  public var blocks: [Block]?
  public var conversationID: String?
  public var data: String?
  public var durationMS: Int?
  public var id: Int?
  public var kind: EventKind
  public var stage: String?
  public var state: EventState?
  public var stream: LogStream?
  public var ts: Date?
  public var turnID: String?

  enum CodingKeys: String, CodingKey {
    case agentID = "agent_id"
    case blocks = "blocks"
    case conversationID = "conversation_id"
    case data = "data"
    case durationMS = "duration_ms"
    case id = "id"
    case kind = "kind"
    case stage = "stage"
    case state = "state"
    case stream = "stream"
    case ts = "ts"
    case turnID = "turn_id"
  }
}

public struct AuditEventListResponse: Sendable, Decodable, Hashable {
  public var data: [AuditEvent]
  public var meta: PageMeta

  enum CodingKeys: String, CodingKey {
    case data = "data"
    case meta = "meta"
  }
}

public struct LogEventListResponse: Sendable, Decodable, Hashable {
  public var data: [LogEvent]
  public var meta: PageMeta

  enum CodingKeys: String, CodingKey {
    case data = "data"
    case meta = "meta"
  }
}

public struct SearchResponse: Sendable, Decodable, Hashable {
  public var data: [SearchHit]
  public var meta: SearchResponse.Meta

  enum CodingKeys: String, CodingKey {
    case data = "data"
    case meta = "meta"
  }
}

public struct APIErrorPayload: Sendable, Decodable, Hashable {
  public var activeSandboxes: Int?
  public var error: String?
  public var errors: JSONValue?
  public var limit: Int?
  public var message: String?
  public var reason: String?
  public var upgradeURL: String?

  enum CodingKeys: String, CodingKey {
    case activeSandboxes = "active_sandboxes"
    case error = "error"
    case errors = "errors"
    case limit = "limit"
    case message = "message"
    case reason = "reason"
    case upgradeURL = "upgrade_url"
  }
}

public struct PendingPermissionRequest: Sendable, Decodable, Hashable {
  public var askedAt: Date?
  public var deadline: Date?
  public var options: [[String: JSONValue]]
  public var requestID: String
  public var tool: String?
  public var turnID: String?

  enum CodingKeys: String, CodingKey {
    case askedAt = "asked_at"
    case deadline = "deadline"
    case options = "options"
    case requestID = "request_id"
    case tool = "tool"
    case turnID = "turn_id"
  }
}

public struct Sandbox: Sendable, Decodable, Hashable, Identifiable {
  public var agentID: String?
  public var checkpoint: Sandbox.Checkpoint?
  public var environmentID: String?
  public var id: String
  public var mode: SandboxMode?
  public var provider: SandboxProvider?
  public var runner: Sandbox.RunnerRef?
  public var spriteName: String?
  public var status: SandboxStatus?
  public var url: String?
  public var vaultID: String?

  enum CodingKeys: String, CodingKey {
    case agentID = "agent_id"
    case checkpoint = "checkpoint"
    case environmentID = "environment_id"
    case id = "id"
    case mode = "mode"
    case provider = "provider"
    case runner = "runner"
    case spriteName = "sprite_name"
    case status = "status"
    case url = "url"
    case vaultID = "vault_id"
  }
}

public struct TurnModelSelection: Sendable, Decodable, Hashable {
  public var effectiveModel: String?
  public var error: String?
  public var requestedModel: String?
  public var source: String?
  public var status: String?

  enum CodingKeys: String, CodingKey {
    case effectiveModel = "effective_model"
    case error = "error"
    case requestedModel = "requested_model"
    case source = "source"
    case status = "status"
  }
}

extension Sandbox {
  public struct Checkpoint: Sendable, Decodable, Hashable, Identifiable {
    public var at: Date?
    public var id: String?

    enum CodingKeys: String, CodingKey {
      case at = "at"
      case id = "id"
    }
  }
}

extension SandboxDetail {
  public struct SandboxConversation: Sendable, Decodable, Hashable, Identifiable {
    public var id: String
    public var insertedAt: Date?
    public var midTurn: Bool?
    public var runtime: Runtime?
    public var status: ConversationStatus?
    public var title: String?

    enum CodingKeys: String, CodingKey {
      case id = "id"
      case insertedAt = "inserted_at"
      case midTurn = "mid_turn"
      case runtime = "runtime"
      case status = "status"
      case title = "title"
    }
  }
}

extension Sandbox {
  public struct RunnerRef: Sendable, Decodable, Hashable, Identifiable {
    public var hostname: String?
    public var id: String?
    public var name: String?
    public var online: Bool?
    public var path: String?

    enum CodingKeys: String, CodingKey {
      case hostname = "hostname"
      case id = "id"
      case name = "name"
      case online = "online"
      case path = "path"
    }
  }
}

public struct Skill: Sendable, Codable, Hashable {
  public var content: String?
  public var name: String?
  public var ref: String?
  public var source: String?

  public init(
    name: String? = nil,
    content: String? = nil,
    source: String? = nil,
    ref: String? = nil
  ) {
    self.name = name
    self.content = content
    self.source = source
    self.ref = ref
  }

  enum CodingKeys: String, CodingKey {
    case content = "content"
    case name = "name"
    case ref = "ref"
    case source = "source"
  }
}

extension Teammate {
  public struct LastTurn: Sendable, Decodable, Hashable, Identifiable {
    public var id: String?
    public var insertedAt: Date?
    public var prompt: String?
    public var status: TurnStatus?
    public var turnNumber: Int?
    public var usage: Usage?

    enum CodingKeys: String, CodingKey {
      case id = "id"
      case insertedAt = "inserted_at"
      case prompt = "prompt"
      case status = "status"
      case turnNumber = "turn_number"
      case usage = "usage"
    }
  }
}

extension Teammate {
  public struct Presence: Sendable, Decodable, Hashable {
    public var label: String?
    public var state: PresenceState

    enum CodingKeys: String, CodingKey {
      case label = "label"
      case state = "state"
    }
  }
}

extension Teammate {
  public struct Preview: Sendable, Decodable, Hashable {
    public var kind: String?
    public var text: String?

    enum CodingKeys: String, CodingKey {
      case kind = "kind"
      case text = "text"
    }
  }
}

extension Catalog {
  public struct Apps: Sendable, Decodable, Hashable {
    public var conversations: String?
    public var team: String?

    enum CodingKeys: String, CodingKey {
      case conversations = "conversations"
      case team = "team"
    }
  }
}

public struct CatalogFirstRequest: Sendable, Decodable, Hashable {
  public var curl: String
  public var placeholders: [String]
  public var prompt: String
  public var typescript: String

  enum CodingKeys: String, CodingKey {
    case curl = "curl"
    case placeholders = "placeholders"
    case prompt = "prompt"
    case typescript = "typescript"
  }
}

public struct CatalogMcpServersItem: Sendable, Decodable, Hashable {
  public var dcr: Bool?
  public var name: String?
  public var slug: String?
  public var url: String?
  public var verifiedOn: String?

  enum CodingKeys: String, CodingKey {
    case dcr = "dcr"
    case name = "name"
    case slug = "slug"
    case url = "url"
    case verifiedOn = "verified_on"
  }
}

extension Catalog {
  public struct SandboxProviders: Sendable, Decodable, Hashable {
    public var `default`: String?
    public var enabled: [String]?

    enum CodingKeys: String, CodingKey {
      case `default` = "default"
      case enabled = "enabled"
    }
  }
}

extension ApplyResult {
  public struct SecretResult: Sendable, Decodable, Hashable {
    public var action: String
    public var errors: JSONValue?
    public var key: String

    enum CodingKeys: String, CodingKey {
      case action = "action"
      case errors = "errors"
      case key = "key"
    }
  }
}

extension AdminUserListResponse {
  public struct Meta: Sendable, Decodable, Hashable {
    public var page: Int
    public var perPage: Int
    public var total: Int

    enum CodingKeys: String, CodingKey {
      case page = "page"
      case perPage = "per_page"
      case total = "total"
    }
  }
}

public struct PageMeta: Sendable, Decodable, Hashable {
  public var hasMore: Bool?
  public var limit: Int?
  public var nextCursor: Int?

  enum CodingKeys: String, CodingKey {
    case hasMore = "has_more"
    case limit = "limit"
    case nextCursor = "next_cursor"
  }
}

extension SearchResponse {
  public struct Meta: Sendable, Decodable, Hashable {
    public var hasMore: Bool
    public var limit: Int
    public var offset: Int

    enum CodingKeys: String, CodingKey {
      case hasMore = "has_more"
      case limit = "limit"
      case offset = "offset"
    }
  }
}
